const developers = [
  {
    id: 0,
    name: "Abhay Raj Singh",
    branch:"Web Development",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 1,
    name: "Tushar Jain",
    branch:"Web Development",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 2,
    name: "Shashank Singh",
    branch:"App Development",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 3,
    name: "Sahil Gupta",
    branch:"App Development",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 4,
    name: "Satyam Kumar",
    branch:"Robotics and IoT",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 5,
    name: "Simran Kulkarni",
    branch:"Robotics and IoT",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 6,
    name: "Sandesh Dudhabaware",
    branch:"Machine Learning",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 7,
    name: "Shashank Singh",
    branch:"Machine Learning",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 8,
    name: "Sandesh Dudhabaware",
    branch:"Competitive Programming",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 9,
    name: "Sahil Gupta",
    branch:"Competitive Programming",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 10,
    name: "Sourav Kumar",
    branch:"AR/VR",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 11,
    name: "Abhay Raj",
    branch:"AR/VR",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 12,
    name: "Sourav Kumar",
    branch:"3D Modelling",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 13,
    name: "Tushar Jain",
    branch:"3D Modelling",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 14,
    name: "Satyam Kumar",
    branch:"Cloud Computing",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },
  {
    id: 15,
    name: "Sourav Kumar",
    branch:"Cloud Computing",
    intro:
      "lorem ipsum lorem ipsum v lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    image: "./images/tushar.jpeg",
    githubLink: "https://google.com",
    linkedinLink: "https://google.com",
    mail: "https://google.com",
    instaLink: "https://google.com",
  },


];
export default developers;
